

python: "2.7"

before_install: sudo apt-get install jython

install:
  - pip install --user -r requirements.txt

before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start

script:
  - jython --version
  - jython -c 'from python.nammu.controller.NammuController import NammuController; a = NammuController()'
