

matrix:
  include:
    - python: 2.7

before_install:
  - export JYTHON_URL='http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar'
  - wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython/bin:$PATH

install:
  - pip install --user -r requirements.txt
  - sudo apt-get install tree
  - tree $HOME/build/oracc/nammu/src/
  - pwd
  - ls
  - javac -d $HOME/build/oracc/nammu/resources/lib $HOME/build/oracc/nammu/src/main/java/uk/ac/ucl/rc/development/oracc/ext/*.java

before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start

script:
  - echo $CLASSPATH
  - echo $JYTHONPATH
  - jython --version
  - jython -c 'from python.nammu.controller.NammuController import NammuController; a = NammuController()'
